apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-app
spec:
  selector:
    name: result-pod
    app: demo-app
  type: NodePort
  ports:
    - targetPort: 80
      port:  80
      nodePort: 30005