apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30005
      targetPort: 80
  selector:
    name: vote-pod
    app: demo-app