apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  selector:
    name: mongo-express

  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 32001
      name: node01
      protocol: TCP