apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongo-pod
  type: ClusterIP
  ports:
    - name: port0
      protocol: TCP
      port: 27017
      targetPort: 27017


