apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-gres-deployment
  labels:
    name: post-gres-deployment
    app: demo-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-app

    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
          ports:
            - containerPort: 5432

