apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: demo-app

spec:
  replicas: 1
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: demo-app
    spec:
      containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: result-pod
      app: demo-app
