apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    name: vote-deployment
    app: demo-app
spec:
  replicas: 1
  template:
    metadata:
      name: vote-pod
      labels:
        name: vote-pod
        app: demo-app
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: vote-pod
      app: demo-app